### ISSUE TITLE
'CertStore' has no attribute 'new_from_host_socket'

### ISSUE THREAD

**Issue by thomasdeniau** [lifehackjim/cert_human#4]
When running

cert_human_cli.py my-host.com                                                                                                                            

I get:

Traceback (most recent call last):
  File "/Users/thomas/homebrew/bin/cert_human_cli.py", line 143, in <module>
    main(cli_args)
  File "/Users/thomas/homebrew/bin/cert_human_cli.py", line 111, in main
    store_obj = store_cls.new_from_host_requests(
AttributeError: type object 'CertStore' has no attribute 'new_from_host_requests'

Python 3.7.4
Requirement already up-to-date: cert_human in /Users/thomas/homebrew/lib/python3.7/site-packages (1.0.7)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3

**Comment by TylerRudie** [comment]
oh good, its not just me

**Comment by pauloneves** [comment]
I downgraded to version 1.0.3 and the error disappeared.
